print("<!DOCTYPE html>")
print("<html lang='pt-br'>")
print("<head>")
print("<title>Python Puro na Web</title>")
print("</head>")
print("<body>")
print("<h1>Hello World</h1>")
print("</body>")
print("</html>")
